"""add social columns to company

Revision ID: 19230de99d2b
Revises: e8e1dff0fc96
Create Date: 2025-10-26 15:11:25.469267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19230de99d2b'
down_revision: Union[str, Sequence[str], None] = 'e8e1dff0fc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.add_column('companies', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('instagram_link', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('linkedin_link', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tiktok_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'tiktok_link')
    op.drop_column('companies', 'linkedin_link')
    op.drop_column('companies', 'instagram_link')
    op.drop_column('companies', 'facebook_url')
    op.create_table('services',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('services_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    # ### end Alembic commands ###
