"""change template column name

Revision ID: 29326343f5f0
Revises: 4ebdaaa2207b
Create Date: 2026-01-05 20:58:50.908911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29326343f5f0'
down_revision: Union[str, Sequence[str], None] = '4ebdaaa2207b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template', sa.String(), nullable=False))
    op.drop_column('templates', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('templates', 'template')
    # ### end Alembic commands ###
