"""change redirect to feedback

Revision ID: 2a495fcfa56b
Revises: 8cc9a4934ee2
Create Date: 2025-12-07 19:13:13.692257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a495fcfa56b'
down_revision: Union[str, Sequence[str], None] = '8cc9a4934ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    op.add_column('messages', sa.Column('is_feedback', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('feedback_response', sa.Enum('positiveResponse', 'negativeResponse', name='respond_enum'), nullable=True))
    op.add_column('messages', sa.Column('feedback_content', sa.String(), nullable=True))
    op.drop_column('messages', 'redirect_response')
    op.drop_column('messages', 'redirect_feedback')
    op.drop_column('messages', 'is_redirect')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_redirect', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('redirect_feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('redirect_response', postgresql.ENUM('positiveResponse', 'negativeResponse', 'messageClicked', name='respond_enum'), autoincrement=False, nullable=True))
    op.drop_column('messages', 'feedback_content')
    op.drop_column('messages', 'feedback_response')
    op.drop_column('messages', 'is_feedback')
    op.create_table('survey',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_pkey'))
    )
    # ### end Alembic commands ###
