"""add invitation relations

Revision ID: 444fcecde846
Revises: 7aa1a34c1a6c
Create Date: 2025-10-30 20:49:44.693191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444fcecde846'
down_revision: Union[str, Sequence[str], None] = '7aa1a34c1a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.add_column('invitations', sa.Column('message_id', sa.UUID(), nullable=True))
    op.alter_column('invitations', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('invitations_client_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invitations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invitations', 'channel')
    op.drop_column('invitations', 'message')
    op.alter_column('messages', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('messages_invitation_id_key'), 'messages', type_='unique')
    op.create_foreign_key(None, 'messages', 'invitations', ['invitation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_unique_constraint(op.f('messages_invitation_id_key'), 'messages', ['invitation_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('messages', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('invitations', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_client_id_fkey'), 'invitations', 'clients', ['client_id'], ['id'])
    op.alter_column('invitations', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('invitations', 'message_id')
    op.create_table('services',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('services_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    # ### end Alembic commands ###
