"""fix survey company fk

Revision ID: 4ebdaaa2207b
Revises: dc7d1f765aef
Create Date: 2025-12-30 19:57:21.276390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebdaaa2207b'
down_revision: Union[str, Sequence[str], None] = 'dc7d1f765aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'survey_analytic', ['survey_id'])
    op.drop_constraint(op.f('survey_analytic_survey_id_fkey'), 'survey_analytic', type_='foreignkey')
    op.create_foreign_key(None, 'survey_analytic', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_analytic', type_='foreignkey')
    op.create_foreign_key(op.f('survey_analytic_survey_id_fkey'), 'survey_analytic', 'companies', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'survey_analytic', type_='unique')
    # ### end Alembic commands ###
