"""remove template type

Revision ID: 4ed55a62bc42
Revises: 29326343f5f0
Create Date: 2026-01-05 20:59:26.680837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed55a62bc42'
down_revision: Union[str, Sequence[str], None] = '29326343f5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('type', postgresql.ENUM('Email', 'SMS', name='message_type'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
