"""add surname to client

Revision ID: 52ab53f19468
Revises: ff07bd8df0ef
Create Date: 2026-01-13 22:29:58.380722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ab53f19468'
down_revision: Union[str, Sequence[str], None] = 'ff07bd8df0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('surname', sa.String(), nullable=True))
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'surname')
    # ### end Alembic commands ###
