"""add company_id to clients

Revision ID: 609a99e56788
Revises: 910d71f524c5
Create Date: 2025-10-21 21:43:24.245782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609a99e56788'
down_revision: Union[str, Sequence[str], None] = '910d71f524c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('clicks', sa.Column('feedback', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('invitations', sa.Column('tracking_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'tracking_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'company_id')
    op.drop_column('clicks', 'feedback')
    op.drop_column('clicks', 'status')
    # ### end Alembic commands ###
