"""add completed prop to message model

Revision ID: 66eca1888d3b
Revises: 8e75b75effb2
Create Date: 2025-11-15 15:51:09.700134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66eca1888d3b'
down_revision: Union[str, Sequence[str], None] = '8e75b75effb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'redirect_response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('redirect_response_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'completed_at')
    op.drop_column('messages', 'completed')
    # ### end Alembic commands ###
