"""add created_at to template model

Revision ID: 87d345538998
Revises: 4ed55a62bc42
Create Date: 2026-01-06 19:08:30.857986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d345538998'
down_revision: Union[str, Sequence[str], None] = '4ed55a62bc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('templates', 'public_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('public_template', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('templates', 'created_at')
    op.drop_column('templates', 'description')
    # ### end Alembic commands ###
