"""change redirect props in message model

Revision ID: 8e75b75effb2
Revises: 5241d357d328
Create Date: 2025-11-15 15:48:20.072023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e75b75effb2'
down_revision: Union[str, Sequence[str], None] = '5241d357d328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('redirect_response', sa.Enum('positiveResponse', 'negativeResponse', name='respond_enum'), nullable=True))
    op.add_column('messages', sa.Column('redirect_response_time', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'responded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('responded', postgresql.ENUM('positiveResponse', 'negativeResponse', 'messageClicked', name='respond_enum'), autoincrement=False, nullable=True))
    op.drop_column('messages', 'redirect_response_time')
    op.drop_column('messages', 'redirect_response')
    # ### end Alembic commands ###
