"""fix fk

Revision ID: 8eead4a5d788
Revises: 444fcecde846
Create Date: 2025-10-30 20:54:11.863387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eead4a5d788'
down_revision: Union[str, Sequence[str], None] = '444fcecde846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_constraint(op.f('messages_invitation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'invitation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('invitation_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_invitation_id_fkey'), 'messages', 'invitations', ['invitation_id'], ['id'], ondelete='CASCADE')
    op.create_table('services',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('services_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    # ### end Alembic commands ###
