"""connect company with survey

Revision ID: 9b7776558d29
Revises: e6a6cc1f83d9
Create Date: 2025-12-08 21:14:12.956695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7776558d29'
down_revision: Union[str, Sequence[str], None] = 'e6a6cc1f83d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('surveys_company_id_fkey'), 'surveys', type_='foreignkey')
    op.create_foreign_key(None, 'surveys', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.create_foreign_key(op.f('surveys_company_id_fkey'), 'surveys', 'companies', ['company_id'], ['id'])
    op.alter_column('surveys', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
