"""add questions columns

Revision ID: d7e699d13d2d
Revises: d0d155e830df
Create Date: 2025-12-08 21:01:11.452614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e699d13d2d'
down_revision: Union[str, Sequence[str], None] = 'd0d155e830df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback_question', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('rating_question', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'rating_question')
    op.drop_column('messages', 'feedback_question')
    # ### end Alembic commands ###
