"""add survey analytic table

Revision ID: da67c7bb0e50
Revises: f238e9bfb83f
Create Date: 2025-12-29 20:50:35.186935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da67c7bb0e50'
down_revision: Union[str, Sequence[str], None] = 'f238e9bfb83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('completed_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'completed_times')
    # ### end Alembic commands ###
