"""recreate current schema

Revision ID: dbd0476fcf90
Revises: 
Create Date: 2025-11-11 12:21:24.636703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd0476fcf90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tracking_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('clicked_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('simple_feedback', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('rating', sa.String(), nullable=True))
    op.drop_column('messages', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'rating')
    op.drop_column('messages', 'simple_feedback')
    op.drop_column('messages', 'clicked_at')
    op.drop_column('messages', 'tracking_id')
    # ### end Alembic commands ###
