"""connect company with survey

Revision ID: e6a6cc1f83d9
Revises: 20bef9feee7e
Create Date: 2025-12-08 21:12:50.905503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a6cc1f83d9'
down_revision: Union[str, Sequence[str], None] = '20bef9feee7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'company_id')
    # ### end Alembic commands ###
