"""template - message connection

Revision ID: ff07bd8df0ef
Revises: becba8222ba6
Create Date: 2026-01-07 22:12:22.046750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff07bd8df0ef'
down_revision: Union[str, Sequence[str], None] = 'becba8222ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'template_id')
    # ### end Alembic commands ###
